SELECT * FROM BD_N2H;
SELECT * FROM BD_H2N;
SELECT * FROM BD_NASUSR;

SELECT * FROM BD_NHTEST;



create table BD_NASUSR(
                          F_ID int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
                          USERNAME varchar(100) NOT NULL ,
                          PASSWORD varchar NOT NULL
);

create table BD_H2N(
                       F_ID int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
                       MSGID varchar  ,
                       MSGTYPE varchar  ,
                       REPLYTO varchar  ,
                       TIMESTAMP timestamp  ,
                       FACILITY varchar  ,
                       ACTION varchar ,
                       SENDER varchar  ,
                       RECEIVER varchar  ,
                       DATA text  ,
                       S_ID bigint  ,
                       STATUS varchar  ,
                       TEST varchar  ,
                       ERRCODE int  ,
                       ERRTEXT varchar  ,
                       DT timestamp  ,
                       USERID varchar
);

create table BD_N2H(
                       F_ID int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
                       MSGID varchar  ,
                       MSGTYPE varchar  ,
                       REPLYTO varchar  ,
                       TIMESTAMP timestamp  ,
                       FACILITY varchar  ,
                       ACTION varchar ,
                       SENDER varchar  ,
                       RECEIVER varchar  ,
                       DATA text  ,
                       S_ID bigint  ,
                       STATUS varchar  ,
                       TEST varchar  ,
                       ERRCODE int  ,
                       ERRTEXT varchar  ,
                       DT timestamp  ,
                       USERID varchar
);